export const FETCH_COMPANY_OWNERS = 'FETCH_COMPANY_OWNERS';
export const SET_FETCH_COMPANY_OWNERS = 'SET_FETCH_COMPANY_OWNERS';
export const SET_FETCH_COMPANY_OWNERS_ERROR = 'SET_FETCH_COMPANY_OWNERS_ERROR';
