export const POPULATE_SMS_TEMPLATES = 'POPULATE_SMS_TEMPLATES';
export const SET_SMS_TEMPLATES_STATUS = 'SET_SMS_TEMPLATES_STATUS';
export const SET_SMS_TEMPLATES_ERROR = 'SET_SMS_TEMPLATES_ERROR';
export const POPULATE_QUICK_REPLIES = 'POPULATE_QUICK_REPLIES';
