export const FETCH_CAMPAIGN_STATS = 'FETCH_CAMPAIGN_STATS';
export const FETCH_CAMPAIGN_STATS_SUCCESS = 'FETCH_CAMPAIGN_STATS_SUCCESS';
export const FETCH_CAMPAIGN_STATS_ERROR = 'FETCH_CAMPAIGN_STATS_ERROR';
