export const SET_ACTIVE_CAMPAIGN = 'SET_ACTIVE_CAMPAIGN';
export const SET_ACTION_BTN_STATUS = 'SET_ACTION_BTN_STATUS';
export const SET_ACTIVE_PROSPECT = 'SET_ACTIVE_PROSPECT';
export const CLEAR_ACTIVE_CAMPAIGN = 'CLEAR_ACTIVE_CAMPAIGN';

// for cycling feature
export const SET_PROSPECT_CYCLE_SOURCE_PATH = 'SET_PROSPECT_CYCLE_SOURCE_PATH';
export const CLEAR_PROSPECT_CYCLE_SOURCE_PATH = 'CLEAR_PROSPECT_CYCLE_SOURCE_PATH';
