export const FETCH_MARKETS = 'FETCH_MARKETS';
export const SET_FETCH_MARKETS = 'SET_FETCH_MARKETS';
export const SET_FETCH_MARKETS_ERROR = 'SET_FETCH_MARKETS_ERROR';

export const DECREMENT_MARKET_CAMPAIGN_COUNT = 'DECREMENT_MARKET_CAMPAIGN_COUNT';
