export const SET_PROSPECT_DATA = 'SET_PROSPECT_DATA';
export const SET_PROSPECT_CAMPAIGNS = 'SET_PROSPECT_CAMPAIGNS';
export const SET_PROSPECT_FETCH_STATUS = 'SET_PROSPECT_FETCH_STATUS';
export const SET_PROSPECT_SMS_RELAY_MAP = 'SET_PROSPECT_SMS_RELAY_MAP';
export const SET_PROSPECT_CAMPAIGN_ID = 'SET_PROSPECT_CAMPAIGN_ID';
export const SET_PROSPECT_UPDATE_ACTION_STATUS = 'SET_PROSPECT_UPDATE_ACTION_STATUS';
export const CLEAR_PROSPECT_CAMPAIGN_ID = 'CLEAR_PROSPECT_CAMPAIGN_ID';
