export const FETCH_PHONE_NUMBERS = 'FETCH_PHONE_NUMBERS';
export const FETCH_PHONE_NUMBERS_SUCCESS = 'FETCH_PHONE_NUMBERS_SUCCESS';
export const FETCH_PHONE_NUMBERS_ERROR = 'FETCH_PHONE_NUMBERS_ERROR';

export const UPDATE_PHONE_NUMBER = 'UPDATE_PHONE_NUMBER ';
