export const SET_CAMPAIGN_DESKTOP_PAGE_ACTIVE_TAB = 'SET_CAMPAIGN_DESKTOP_PAGE_ACTIVE_TAB';
export const SET_CAMPAIGN_DESKTOP_PAGE_ACTIVE_SORT = 'SET_CAMPAIGN_DESKTOP_PAGE_ACTIVE_SORT';
export const SET_CAMPAIGN_DESKTOP_TAB_DATA = 'SET_CAMPAIGN_DESKTOP_TAB_DATA';
export const RESET_CAMPAIGN_LIST_FILTER_TABS = 'RESET_CAMPAIGN_LIST_FILTER_TABS';
export const SET_ACTIVE_CAMPAIGN_PROSPECT = 'SET_ACTIVE_CAMPAIGN_PROSPECT';
