export const SET_PROSPECTS_SEARCH_STATUS = 'SET_PROSPECTS_SEARCH_STATUS';
export const SET_SEARCHED_PROSPECTS = 'SET_SEARCHED_PROSPECTS';
export const SET_SEARCH_PROSPECTS_ERROR = 'SET_SEARCH_PROSPECTS_ERROR';
export const SET_MORE_PROSPECTS = 'SET_MORE_PROSPECTS';
export const RESET_PROSPECT_DATA = 'RESET_PROSPECT_DATA';
export const SET_PROSPECTS_FETCH_MORE_STATUS = 'SET_PROSPECTS_FETCH_MORE_STATUS';
