export const POPULATE_PROSPECT_NOTES = 'POPULATE_PROSPECT_NOTES';
export const SET_PROSPECT_NOTE_ERROR = 'SET_PROSPECT_NOTE_ERROR';
export const SET_PROSPECT_NOTES_STATUS = 'SET_PROSPECT_NOTES_STATUS';
export const ADD_PROSPECT_NOTE = 'ADD_PROSPECT_NOTE';
export const DELETE_PROSPECT_NOTE = 'DELETE_PROSPECT_NOTE';
export const EDIT_PROSPECT_NOTE = 'EDIT_PROSPECT_NOTE';
export const RESTORE_PROSPECT_NOTE = 'RESTORE_PROSPECT_NOTE';
